//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class img_paths_social {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal img_paths_social() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.img_paths_social", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /img/facebook_white.png.
        /// </summary>
        internal static string facebook {
            get {
                return ResourceManager.GetString("facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /img/instagram_white.png.
        /// </summary>
        internal static string instagram {
            get {
                return ResourceManager.GetString("instagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /img/linkedin_white.png.
        /// </summary>
        internal static string linkedin {
            get {
                return ResourceManager.GetString("linkedin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /img/pinterest_white.png.
        /// </summary>
        internal static string pinterest {
            get {
                return ResourceManager.GetString("pinterest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /img/twitter_white.png.
        /// </summary>
        internal static string twitter {
            get {
                return ResourceManager.GetString("twitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /img/wordpress_white.png.
        /// </summary>
        internal static string wordpress {
            get {
                return ResourceManager.GetString("wordpress", resourceCulture);
            }
        }
    }
}
